options:
  max_depth: 10

stages:
  - build

# Build the Docker image to verify it works
build_image:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - docker build -t carefate-app .
    - echo "Build successful!"
